/***************************************************************************
 *   Copyright (C) 2008 - 2009 by Dario Freddi                             *
 *   drf@chakra-project.org                                                *
 *   Copyright (C) 2008 by Lukas Appelhans				   				   *
 *   l.appelhans@gmx.de							   						   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.          *
 ***************************************************************************/
 
/* This file has been autogenerated by CMake!!! Don't edit it unless you're 
 * totally out of your goddamn mind!
 */ 
 
#ifndef CONFIG_H
#define CONFIG_H

/* Defines the Image Installation Path */
#define IMAGE_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/tribe/images"

/* Defines the Music Installation Path */
#define MUSIC_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/tribe/music"

/* Defines Scripts Installation Path */
#define SCRIPTS_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/tribe/scripts/"

/* Defines Configs Installation Path */
#define CONFIG_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/tribe/config/"

/* Defines the Stylesheet Installation Path */
#define STYLESHEET_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/share/tribe/style/tribe.qss"

/* Defines the Installation Path */
#define TRIBE_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}"

/* Defines Tribe Build Revision (will appear on UI) */
#define TRIBE_BUILD_REVISION "source build/from git"

/* Defines Target Mount Point */
#define INSTALLATION_TARGET "/mnt/tribeinstall"

/* Defines KDEmod repo */
#define KDEMOD_REPO "core"

/* Defines Tribe Package name */
#define TRIBE_PACKAGE "kdemod-tribe"

/* Defines Tribe Partitionmanager Package name */
#define TRIBE_PARTITIONMANAGER_PACKAGE "kdemod-tribe-partitionmanager"

/* Defines TribeLauncher worker executable location */
#define TRIBE_LAUNCHER_WORKER_EXECUTABLE "${LIB_INSTALL_DIR}/tribe/tribelauncherworker"

/* Defines Arxin Package name */
#define ARXIN_PACKAGE "kdemod-arxin"

/* Defines the version */
#define TRIBE_VERSION "1.0 alpha"

#endif /*CONFIG_H*/
