#!/bin/bash

job_install_burg()
{
    trap error_handler ERR

    msg_job_start "job_install_burg"

    msg "mount chroot"
    mount -v -t proc none ${mountpoint}/proc
    mount -v -t sysfs none ${mountpoint}/sys
    mount -v -o bind /dev ${mountpoint}/dev
    mount -v -o bind /dev/pts ${mountpoint}/dev/pts

    msg "installing burg"
    _device=$(echo ${target_boot} | cut -b1-3)
    echo "BURG____ >>>> mountpoint: ${mountpoint}"
    echo "BURG____ >>>> target_boot: ${target_boot}"
    echo "BURG____ >>>> device: ${_device}"
    chroot ${mountpoint} burg-install /dev/${_device} > /tmp/burg.log 2>&1

    msg "generating []/boot/burg/burg.cfg"
    chroot ${mountpoint} burg-mkconfig -o /boot/burg/burg.cfg

    msg "copying installation logs to target /var/log"
    if [ -e "/tmp/installation.log" ] ; then
        cp -v -f /tmp/installation.log ${mountpoint}/var/log/installation.log
    fi

    if [ -e "/tmp/initramfs.log" ] ; then
        cp -v -f /tmp/initramfs.log ${mountpoint}/var/log/installation-initramdisk.log
    fi

    if [ -e "/tmp/burg.log" ] ; then
        cp -v -f /tmp/burg.log ${mountpoint}/var/log/installation-burg.log
    fi

    msg "umounting /proc, /sys, /dev/pts and /dev"
    umount -v ${mountpoint}/proc ${mountpoint}/sys ${mountpoint}/dev/pts ${mountpoint}/dev  

    msg_job_done
}
