#!/bin/bash

job_setup_xorg()
{
	# initialize error handling
	trap error_handler ERR

	msg_job_start "job_setup_xorg"

	# copy generated xorg.xonf to target
	if [ -e "/.livesys/overlay/etc/X11/xorg.conf" ] ; then
		msg "copying generated xorg.conf to target"
		cp -v /.livesys/overlay/etc/X11/xorg.conf ${mountpoint}/etc/X11/xorg.conf
	fi

	# copy HAL input config to target
	if [ -e "/.livesys/overlay/etc/hal/fdi/policy/10-keymap.fdi" ] ; then
		msg "copying HAL input config to target"
		cp -vf /.livesys/overlay/etc/hal/fdi/policy/10-keymap.fdi ${mountpoint}/etc/hal/fdi/policy/10-keymap.fdi
	fi

	msg_job_done
}
