#!/bin/bash

job_create_menulst()
{
	# initialize error handling
	trap error_handler ERR

	msg_job_start "job_create_menulst"

	msg "converting ${grub_device} to a valid device"
	# cut ${grub_device}
	grub_device=`echo ${grub_device} | cut -c3`

	if [ ${grub_device} == "a" ] ; then
	    grub_device=0
	elif [ ${grub_device} == "b" ] ; then
	    grub_device=1
	elif [ ${grub_device} == "c" ] ; then
	    grub_device=2
	elif [ ${grub_device} == "d" ] ; then
	    grub_device=3
	elif [ ${grub_device} == "e" ] ; then
	    grub_device=4
	elif [ ${grub_device} == "f" ] ; then
	    grub_device=5
	elif [ ${grub_device} == "g" ] ; then
	    grub_device=6
	elif [ ${grub_device} == "h" ] ; then
	    grub_device=7
	elif [ ${grub_device} == "i" ] ; then
	    grub_device=8
	elif [ ${grub_device} == "j" ] ; then
	    grub_device=9
	elif [ ${grub_device} == "k" ] ; then
	    grub_device=10
	elif [ ${grub_device} == "l" ] ; then
	    grub_device=11
	elif [ ${grub_device} == "m" ] ; then
	    grub_device=12
	elif [ ${grub_device} == "n" ] ; then
	    grub_device=13
	elif [ ${grub_device} == "o" ] ; then
	    grub_device=14
	elif [ ${grub_device} == "p" ] ; then
	    grub_device=15
	elif [ ${grub_device} == "q" ] ; then
	    grub_device=16
	elif [ ${grub_device} == "r" ] ; then
	    grub_device=17
	elif [ ${grub_device} == "s" ] ; then
	    grub_device=18
	elif [ ${grub_device} == "t" ] ; then
	    grub_device=19
	elif [ ${grub_device} == "u" ] ; then
	    grub_device=20
	elif [ ${grub_device} == "v" ] ; then
	    grub_device=21
	elif [ ${grub_device} == "w" ] ; then
	    grub_device=22
	elif [ ${grub_device} == "x" ] ; then
	    grub_device=23
	elif [ ${grub_device} == "y" ] ; then
	    grub_device=24
	elif [ ${grub_device} == "z" ] ; then
	    grub_device=25
	fi
    
	msg "create /boot/grub"
	mkdir -p ${mountpoint}/boot/grub

	msg "copying menu.lst from livesystem to target"
	cp -v -f /etc/skel/menu.lst ${mountpoint}/boot/grub

	msg "cleaning target menu.lst at first"
	cat ${mountpoint}/boot/grub/menu.lst | grep -v title | grep -v root | grep -v kernel | grep -v initrd | grep -v map | grep -v chainloader | grep -v makeactive | grep -v splashimage | grep -v Chakra >> ${mountpoint}/boot/grub/menu.lst.new

	msg "starting menu.lst config"

	if [ "${use_swap}" = "yes" ] ; then

	msg "we are using swap partition"

		_sdevice=`echo /dev/${target_swap}`
		_suuid=`blkid "${_sdevice}" -s UUID -o value`
	fi

	if [ "${use_boot}" = "yes" ] ; then
		msg "we are using a separate /boot partition"
	else
		msg "we are not using a separate /boot partition"
		_boot="/boot"
	fi

	_device=`echo /dev/${target_root}`
	_uuid=`blkid "${_device}" -s UUID -o value`

	# add options
	echo " " >>${mountpoint}/boot/grub/menu.lst.new
	echo "hiddenmenu" >>${mountpoint}/boot/grub/menu.lst.new
	echo "default 0" >>${mountpoint}/boot/grub/menu.lst.new
	echo "timeout 1" >>${mountpoint}/boot/grub/menu.lst.new
		
	# standard startup entry
	msg "adding standard entry"
	echo " " >>${mountpoint}/boot/grub/menu.lst.new
	echo "# (0) Chakra GNU/Linux" >>${mountpoint}/boot/grub/menu.lst.new
	echo "title Chakra GNU/Linux" >>${mountpoint}/boot/grub/menu.lst.new

	echo "root (hd${grub_device},${grub_partition})" >>${mountpoint}/boot/grub/menu.lst.new
	if [ "${use_swap}" = "yes" ] ; then
		echo "kernel ${_boot}/vmlinuz26 resume=/dev/disk/by-uuid/${_suuid} root=/dev/disk/by-uuid/${_uuid} ro" >>${mountpoint}/boot/grub/menu.lst.new
	else
		echo "kernel ${_boot}/vmlinuz26 root=/dev/disk/by-uuid/${_uuid} ro" >>${mountpoint}/boot/grub/menu.lst.new
	fi
	echo "initrd ${_boot}/kernel26.img" >>${mountpoint}/boot/grub/menu.lst.new

	# fallback startup entry
	msg "adding fallback entry"
	echo " " >>${mountpoint}/boot/grub/menu.lst.new
	echo "# (1) Chakra GNU/Linux Fallback" >>${mountpoint}/boot/grub/menu.lst.new
	echo "title Chakra GNU/Linux Fallback" >>${mountpoint}/boot/grub/menu.lst.new

	echo "root (hd${grub_device},${grub_partition})" >>${mountpoint}/boot/grub/menu.lst.new
	if [ "${use_swap}" = "yes" ] ; then
		echo "kernel /boot/vmlinuz26 resume=/dev/disk/by-uuid/${_suuid} root=/dev/disk/by-uuid/${_uuid} ro" >>${mountpoint}/boot/grub/menu.lst.new
	else
		echo "kernel /boot/vmlinuz26 root=/dev/disk/by-uuid/${_uuid} ro" >>${mountpoint}/boot/grub/menu.lst.new
	fi
	echo "initrd /boot/kernel26-fallback.img" >>${mountpoint}/boot/grub/menu.lst.new

	# install new menu.lst
	msg "installing menu.lst to target"
	rm -rf ${mountpoint}/boot/grub/menu.lst
	mv ${mountpoint}/boot/grub/menu.lst.new ${mountpoint}/boot/grub/menu.lst

	unset _uuid
	unset _device

	msg_job_done
}
