#!/bin/bash

job_install_burg()
{
    trap error_handler ERR

    msg_job_start "job_install_burg"

    msg "mount chroot"
    mount -v -t proc none ${mountpoint}/proc
    mount -v -t sysfs none ${mountpoint}/sys
    mount -v -o bind /dev ${mountpoint}/dev
    mount -v -o bind /dev/pts ${mountpoint}/dev/pts

    msg "installing burg"
    _device=$(echo ${target_boot} | cut -b1-3)
    echo "BURG____ >>>> mountpoint: ${mountpoint}"
    echo "BURG____ >>>> target_boot: ${target_boot}"
    echo "BURG____ >>>> device: ${_device}"
    chroot ${mountpoint} burg-install /dev/${_device} --no-floppy > /tmp/burg.log 2>&1

    if [ -e "/tmp/catalyst" ] ; then
       msg "Adding nomodeset for catalyst to kernel line"
       sed -i -e "s,GRUB_CMDLINE_LINUX_DEFAULT=.*,GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash radeon.modeset=0\",g" ${mountpoint}/default/burg
       sed -i -e "s,GRUB_CMDLINE_LINUX=.*,GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash radeon.modeset=0\",g" ${mountpoint}/default/burg
    fi

    msg "generating []/boot/burg/burg.cfg"
    chroot ${mountpoint} burg-mkconfig -o /boot/burg/burg.cfg --skip-resume

    if [ "${use_swap}" = "yes" ] ; then
       msg "we are using swap partition"
       _sdevice=`echo /dev/${target_swap}`
       _suuid=`blkid "${_sdevice}" -s UUID -o value`
       sed -i -e "s~root=/dev~resume=/dev/disk/by-uuid/${_suuid} root=/dev~g" ${mountpoint}/boot/burg/burg.cfg
    fi

    msg "umounting /proc, /sys, /dev/pts and /dev"
    umount -v ${mountpoint}/proc ${mountpoint}/sys ${mountpoint}/dev/pts ${mountpoint}/dev  

    msg_job_done
}
